### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by CaitSith2** [simonmkwii/NCABuilder#2]
Just wanted to let you know that your project doesn't have a license. This means that you own the copyright to the code, and this isn't good (at least from an open source developer's perspective), here's why in the words of [choosealicense.com](https://choosealicense.com/no-permission/):

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

Can you please add a license to your code? I recommend either using MIT or GPLv2.

(Was mainly looking to use some of your crypto code, so that I could remove my external dependency of hactool within [Switch SD to NSP dumper](https://github.com/CaitSith2/SwitchSDTool), without needing to rewrite the crypto from scratch.

**Comment by jakibaki** [comment]
You might want to look into [libhac](https://github.com/Thealexbarney/libhac).  
It already has nsp-dumping support and can be integrated as a library without any hactool dependency.

But yeah I second that this really ought to get a license.

**Comment by CaitSith2** [comment]
Thanks for pointing me in a direction that will be more helpful for my tool.  It has a fair bit of functionality, where I can allow for skipping even hacdiskmount altogether.

**Comment by simontime** [comment]
I have chosen the MIT license, so I'll close this issue.
